name: example_project
description: "An example project to demonstrate the usage of dart_network_layer_dio package."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  dart_network_layer_dio:
    path: ../dart_network_layer_dio
  dio: ^5.9.2
  flutter:
    sdk: flutter
  openapi:
    path: modules/openapi
  path_provider: ^2.1.5
  remote_logging: ^0.0.2

dev_dependencies:
  build_runner: ^2.12.2
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

dependency_overrides:
  dart_network_layer_core:
    path: ../dart_network_layer_core
dart_network_layer_dio:
  path: ../dart_network_layer_dio

flutter:
  uses-material-design: true
