name: dart_network_layer_dio
description: "Dio implementation for dart_network_layer_core. Uses the dio package to make network requests."
version: 1.0.1
homepage: https://github.com/femrek/dart_network_layer/tree/main/dart_network_layer_dio

resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  dart_network_layer_core: ^1.0.1
  dio: ^5.9.2
  meta: '>=1.14.0 <2.0.0'
  logging: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: ^1.25.14
  http_test_server: ^0.1.1
  very_good_analysis: ^9.0.0
