include: package:very_good_analysis/analysis_options.yaml

exclude:
  - 'test/**'

linter:
  rules:
    sort_pub_dependencies: false
    require_trailing_commas: false
    avoid_function_literals_in_foreach_calls: false
