name: flutter_network_layer
description: "Network manager for Flutter applications"
version: 0.0.1
homepage: https://github.com/femrek/flutter_network_layer

environment:
  sdk: ^3.6.0

dependencies:
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
