name: flutter_network_layer_dio
description: "Dio implementation for flutter_network_layer_core. Uses the dio package to make network requests."
version: 0.4.0
homepage: https://github.com/femrek/flutter_network_layer/tree/main/flutter_network_layer_dio

environment:
  sdk: ^3.6.0

dependencies:
  flutter_network_layer_core: ^0.4.1
  dio: ^5.7.0

dev_dependencies:
  test: ^1.25.14
  http_test_server: ^0.1.0
  very_good_analysis: ^7.0.0
