name: flutter_network_layer_dio
description: "Dio implementation for flutter_network_layer"
version: 0.0.1
homepage: https://github.com/femrek/flutter_network_layer/tree/main/flutter_network_layer_dio

environment:
  sdk: ^3.6.0

dependencies:
  dio: ^5.7.0

dev_dependencies:
  test: ^1.25.14
  very_good_analysis: ^7.0.0
