name: example_flutter_dio
description: "An example Flutter project using the flutter_network_layer_dio package."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # flutter_network_layer Packages
  flutter_network_layer_dio:
    path: ../flutter_network_layer_dio
  ## Alternatively can be added from pub.dev

  # Dependency Injection
  get_it: ^8.0.3

  # Logging
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
