name: flutter_network_layer_core
description: "Core library for flutter_network_layer. Includes base classes of flutter_network_layer project."
version: 0.1.1
homepage: https://github.com/femrek/flutter_network_layer/tree/main/flutter_network_layer_core

environment:
  sdk: ^3.6.0

dev_dependencies:
  test: ^1.25.14
  very_good_analysis: ^7.0.0
