name: flutter_network_layer_core
description: "Core library for flutter_network_layer. Includes base classes of flutter_network_layer project."
version: 0.7.1
homepage: https://github.com/femrek/flutter_network_layer/tree/main/flutter_network_layer_core

resolution: workspace

environment:
  sdk: ^3.6.0

dev_dependencies:
  http: ^1.2.2
  test: ^1.25.14
  very_good_analysis: ^9.0.0
  http_test_server: ^0.1.0
