name: example
description: "The example application for the flutter_network_layer package"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # the package
  flutter_network_layer_core:
    path: ../

  # dependency injection
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
