name: flutter_network_layer
description: "Network manager for Flutter applications"
version: 0.0.1
homepage: https://github.com/femrek/flutter_network_layer/tree/main/flutter_network_layer

environment:
  sdk: ^3.6.0

dependencies:
  flutter_network_layer_dio: ^0.1.1

dev_dependencies:
  test: ^1.25.14
  very_good_analysis: ^7.0.0

