name: Dart Test and Prepare Release

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*' # Release tags for the bundle package
  pull_request:
    branches: [ "main" ]

jobs:
  # Analyze the source code then run the tests
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      # Install dependencies for each package
      - name: Install dependencies for core
        run: dart pub get --no-example -C flutter_network_layer_core
      - name: Install dependencies for dio impl
        run: dart pub get --no-example -C flutter_network_layer_dio

      # Verify that the libraries are error-free
      - name: Verify formatting for core
        run: dart format --output=none --set-exit-if-changed flutter_network_layer_core/lib
      - name: Verify formatting for dio impl
        run: dart format --output=none --set-exit-if-changed flutter_network_layer_dio/lib

      # Analyze the source code
      - name: Analyze project source for core
        run: dart analyze flutter_network_layer_core/lib
      - name: Analyze project source for dio impl
        run: dart analyze flutter_network_layer_dio/lib

      # Run tests
      - name: Run tests for core
        run: cd flutter_network_layer_core && dart test
      - name: Run tests for dio implementation
        run: cd flutter_network_layer_dio && dart test
